### ISSUE TITLE
Any project updates decided offline?

### ISSUE THREAD

**Issue by neensimpson** [vallis/synthlisa#3]
Hi, 

This is Christine from Jon Gair's group. I'm trying to get into using synthlisa to generate some data but looking over the projects and issues it looks like it got a bit stuck in the conversion to Py3 and I'm getting errors I don't understand when I try to run things from the fork I made. 

Is there any work still going on with synthlisa or should I be just talking to the official sim group instead? The reason I wanted to use synthlisa was that I wanted to start with a method that worked for the simpler TDI case and make the data more complicated later. I'm not sure if the sim group do simple TDI.

Cheers,
Christine

**Comment by vallis** [comment]
I would say synthlisa is in legacy/support mode, still useful for some investigations. I thought I had mostly converted it to Python 3, but there may be corners left where it does not work. I'm happy to help you troubleshoot those.

The sim group is working mostly (or only?) with the French simulators LISACode and LISANode.

**Comment by neensimpson** [comment]
Thanks very much, I'll send you those errors in proper detail if I come back to synthlisa but for now it looks like the french simulators are going to be the best option for me.

I've also been in touch with people in the sim group and it looks like I'll be able to collaborate with them, which is great.
